#!/usr/bin/env bash
# Fluidd installation script
# Installs Fluidd and nginx
# Originally Written by Raymond Himle
# With contributions from Meteyou and Cadriel
# With thanks to KevinOConnor & Arksine
# GPL V3
########

# Source error handling, leave this in place
set -Ee

# Set LC_ALL to prevent errors
export LC_ALL=C

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing Fluidd Web Frontend and configuration..."

echo_green "Install Fluidd dependencies ..."
### install all deps at once for time consumption reasons.
## APT: Update Repo Database and install Dependencies
apt_update_skip
# Disabling shellcheck SC2086, because we want "wordsplitting"
# shellcheck disable=SC2086
check_install_pkgs ${FLUIDD_DEPS}


### Preparing nginx
echo_green "Configure nginx webserver ..."
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/fluidd /etc/nginx/sites-enabled/


# lower nginx rotate cycle to 2 instead 14
echo_green "Modify logrotate cycle (14d -> 2d) ..."
sudo sed -i 's/rotate 14/rotate 2/' /etc/logrotate.d/nginx

### Download and Install Fluidd Web Frontend
echo_green "Install Fluidd Web Frontend ..."
pushd /home/"${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" wget -q --show-progress -O fluidd.zip "${FLUIDD_URL}"
sudo -u "${BASE_USER}" unzip fluidd.zip -d /home/"${BASE_USER}"/fluidd
## cleanup
rm /home/"${BASE_USER}"/fluidd.zip


echo_green "Linking log files ..."
# Make sure printer_data/logs exists
if [[ ! -d "/home/${BASE_USER}/printer_data/logs" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "/home/${BASE_USER}/printer_data/logs"
fi
### Link logfiles to klipper_logs
ln -s /var/log/nginx/fluidd-access.log /home/"${BASE_USER}"/printer_data/logs
ln -s /var/log/nginx/fluidd-error.log /home/"${BASE_USER}"/printer_data/logs


### Install mainsail.cfg
## clone repo
echo_green "Installing mainsail.cfg ..."
gitclone FLUIDD_CONFIG_REPO mainsail-config

# Make sure printer_data/config exists
if [[ ! -d "/home/${BASE_USER}/printer_data/config" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "/home/${BASE_USER}/printer_data/config"
fi
if [[ -f "$FLUIDD_CONFIG_SRC_PATH}" ]]; then
    sudo -u "${BASE_USER}" \
    ln -sf "${FLUIDD_CONFIG_SRC_PATH}" "${FLUIDD_CONFIG_DEST_PATH}"
fi

popd &> /dev/null || exit 1
# Unpack root at the end, so files are modified before
unpack /filesystem/root /
